baseurl = "http://betingelser.blankoslo.no"
languageCode = "no-nb"
title = "Betingelser i Blank"
GoogleAnalytics = "UA-66155927-6"

[params]
  intro_title = "Betingelser i Blank"
  intro_text = "Siden vi vet at det kan være vanskelig å holde oversikten over alt som blir sagt i intervjuer og samtaler, finner du her litt mer om våre prinsipper og goder. Håper det kan være til nytte, kanskje til irritasjon, men i alle fall skape diskusjon. "
